### PR TITLE
Adds docker and docker compose instructions

### PR DESCRIPTION
**Pull request by aspic**

### CODE REVIEW

**Comment by Joohansson** [comment]
@aspic I'm trying to follow these instructions in Windows using WSL and docker. I get this on the final copy command
image

I also find the README a bit confusing at
"To run with configuration, first copy default settings:"

It's a bit unclear which directory to be in when doing that. Should be in the server dir, right? And then switch back to /src before doing the docker run command? Or is that done from the src/server dir?

**Comment by aspic** [comment]
Thanks for the feedback @Joohansson :-) I haven't tested this on Windows, so I'll check whether this some quirk there to be aware of. Will also clarify in README.

**Comment by aspic** [comment]
Updated Dockerfile and added a few clarifications to the readme. Please try again.

**Comment by Joohansson** [comment]
Nice work and a good addition to the project. Works fine now!

**Pull request merged**
